---
title: "Study Map"
author: "Daniel Gschwentner"
date: "2025-02-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(root.dir = "C:/Users/DanielGschwentner/OneDrive - University of Nebraska-Lincoln/Sandhills LimnoSat lake color v2")
```

```{r}
rm(list = ls())
library(tidyverse)
library(sf)
source("code/theme_R.r")
```


## Load data sets

```{r}
st_layers(dsn = "data/GIS/sandhill_lakes.gpkg")

# load GIS data
gw.lakes <- st_read(dsn = "data/GIS/sandhill_lakes.gpkg", layer = "selected_lakes_groundwater")
gw.wells <- st_read(dsn = "data/GIS/sandhill_lakes.gpkg", layer = "final_groundwater_wells")
# cast to GIS
all.lakes <- read_csv("data/Sandhills_limnosat_no_winter_17Feb25.csv") %>%
  select(Hylak_id, lat, lon, dWL) %>% group_by(Hylak_id) %>% summarise_all(.funs = median) %>%
  st_as_sf(coords = c("lon", "lat"))
st_crs(all.lakes) <- 3857

# supporting data
sandhills <- st_read(dsn = "data/GIS/USA_ECOREGIONS.gpkg", layer = "USA_ECOREGIONS_LEVEL_3") %>% 
  filter(NA_L3NAME == "Nebraska Sand Hills") %>%
  st_transform(., crs = st_crs(all.lakes))
ne <- st_read(dsn = "data/GIS/USA_STATES.gpkg", layer = "NE") %>% 
  st_transform(., crs = st_crs(all.lakes))
usa <- st_read(dsn = "data/GIS/USA_STATES.gpkg", layer = "USA_STATES_CONTER") %>% 
  st_transform(., crs = st_crs(all.lakes))

```

## Create background map

```{r}
(bg.map <- ggplot() + 
  geom_sf(data = usa, fill = "white") + 
   geom_sf(data = sandhills, fill = "black") + 
   theme_void())
```
## Map of study sites

```{r}

(study.sites <- ggplot() + 
  geom_sf(data = sandhills, lwd = 0.75, col = "black", fill = "white") + 
  geom_sf(data = all.lakes, aes(fill = "Study lakes"), col = "white", stroke = 0.2, pch = 21, size = 2) + 
  geom_sf(data = gw.lakes, aes(fill = "GW lakes"), col = "white", stroke = 0.2, pch = 21, size = 2) + 
  geom_sf(data = gw.wells, aes(fill = "GW wells"), col = "white", stroke = 0.2, pch = 21, size = 2) + 
  scale_fill_manual(values = c("Study lakes" = "black", "GW lakes" = "blue", "GW wells" = "red")) + 
  labs(fill = NULL) + 
  theme_void() + theme(legend.position = "bottom"))

```
## Map of mean lake color

```{r}
# figure of dominant lake color across all samples
# reload data
limnosat <- read_csv("data/Sandhills_limnosat_no_winter_17Feb25.csv") # no winter obs
# classify
color.class <- limnosat %>%
  mutate(group = ifelse(dWL <= 495, "Blue", 
                        ifelse(dWL >= 560, "Brown", "Green"))) %>%# n obs per lake
  group_by(Hylak_id) %>%
  mutate(all.n = n()) %>% ungroup() %>%
  # n group level obs
  group_by(Hylak_id, group) %>%
  summarise(n = n(), all.n = mean(all.n)) %>% ungroup() %>%
  mutate(perc.group = round(n * 100/all.n, 0)) %>%
  # long to wide
  pivot_wider(id_cols = Hylak_id, names_from = group, values_from = perc.group) %>%
  mutate_at(2:4, .funs = function(x) { ifelse(is.na(x), 0, x)}) %>%
  # classify into color groups
  mutate(col.group = ifelse(Blue >= 60, "Blue",
                            ifelse(Brown >= 60, "Brown", 
                                   ifelse(Green >= 60, "Green", 
                                          ifelse(Blue >= 40 & Green >= 20, "Blue-green", 
                                                 ifelse(Green >= 40 & Brown >= 20, "Green-brown",
                                                        ifelse(Blue >= 40 & Brown >= 20, "Blue-brown", ifelse(Brown >= 40 & Green >= 20, "Brown-green", NA))))))))

# merge with lake data
all.lakes <- merge(all.lakes, color.class, by = "Hylak_id")

# create legend for color classes
cols.fill <- c("Blue" = "blue", "Blue-brown" = "blueviolet", "Blue-green" = "slateblue",
                 "Brown" = "brown", "Brown-green" = "darkorange", 
               "Green" = "forestgreen", "Green-blue" = "greenyellow", "Green-brown" = "olivedrab")
```

```{r}

(dwl.map <- ggplot() + 
  geom_sf(data = sandhills, lwd = 0.75, col = "black", fill = "white") + 
  geom_sf(data = all.lakes, aes(fill = col.group), pch = 21, size = 2, stroke = 0.1, col = "white") + 
  scale_fill_manual(values = cols.fill) + 
  labs(fill = NULL) + 
  theme_void() + theme(legend.position = "bottom"))

```

## Arrange all together into map

```{r}
library(ggpubr)

map.all <- ggarrange(plotlist = list(study.sites, dwl.map, bg.map), 
                     align = "hv", ncol = 3, labels = letters[1:3])

map.all


ggsave(filename = "figures/maps.jpg", map.all, width = 12, height = 2.5)

ggsave(filename = "figures/basemap.jpg", bg.map, width = 7, height = 5, dpi = 600)
ggsave(filename = "figures/study_sites.png", study.sites, width = 4, height = 3, dpi = 600)
ggsave(filename = "figures/dwl_map.png", dwl.map, width = 4, height = 3, dpi = 600)
```

